<a href="https://colab.research.google.com/github/808819/CIE/blob/main/4A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_excel(r'top_seeker_searches_all_data.xlsx')
df. head(10)
df.info()
df.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9847 entries, 0 to 9846
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   keywords_modified  9847 non-null   object 
 1   Company            9846 non-null   float64
 2   Designation        9847 non-null   int64  
 3   Function           9847 non-null   int64  
 4   Role               9847 non-null   int64  
 5   Skills             9847 non-null   int64  
 6   Location           9847 non-null   int64  
 7   tenant             6502 non-null   object 
 8   result_count       6532 non-null   float64
 9   search_count       6554 non-null   float64
 10  source             6568 non-null   object 
 11  Unnamed: 11        0 non-null      float64
 12  Unnamed: 12        0 non-null      float64
 13  Unnamed: 13        10 non-null     object 
dtypes: float64(5), int64(5), object(4)
memory usage: 1.1+ MB


Company  Designation     Function         Role       Skills  \
count  9846.000000  9847.000000  9847.000000  9847.000000  9847.000000   
mean      0.145338     0.262923     0.037372     0.162994     0.466843   
std       0.352459     0.440243     0.189681     0.369379     0.498925   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     1.000000     0.000000     0.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

          Location   result_count  search_count  Unnamed: 11  Unnamed: 12  
count  9847.000000    6532.000000   6554.000000          0.0          0.0  
mean      0.011476    5242.551898     14.083766          NaN          NaN  
std       0.106513   13987.249447    122.924962          NaN          NaN  
min       0.000000       1.000000      2.000000          NaN          NaN  
25%       0.000000     120.000000      3.000000          NaN          NaN  
50%       0.000000     653.500000      4.000000          NaN          NaN  
75%       0.000000    3475.000000     10.000000          NaN          NaN  
max       1.000000  302190.000000   8472.000000          NaN          NaN

In [ ]:
df.duplicated().sum()
df[ "Company" ].unique()


array([ 0.,  1., nan])

In [ ]:
df.isnull().sum()

keywords_modified       0
Company                 1
Designation             0
Function                0
Role                    0
Skills                  0
Location                0
tenant               3345
result_count         3315
search_count         3293
source               3279
Unnamed: 11          9847
Unnamed: 12          9847
Unnamed: 13          9837
dtype: int64

In [ ]:
df.replace(np.nan,0,inplace = True)
df.isnull().sum()

keywords_modified    0
Company              0
Designation          0
Function             0
Role                 0
Skills               0
Location             0
tenant               0
result_count         0
search_count         0
source               0
Unnamed: 11          0
Unnamed: 12          0
Unnamed: 13          0
dtype: int64

In [ ]:
 df.dtypes

keywords_modified     object
Company              float64
Designation            int64
Function               int64
Role                   int64
Skills                 int64
Location               int64
tenant                object
result_count         float64
search_count         float64
source                object
Unnamed: 11          float64
Unnamed: 12          float64
Unnamed: 13           object
dtype: object

In [ ]:
# Define scalars
number_of_units = 598
mass_of_sun = 1.989630
length_great_wall_of_china = 21196
print(number_of_units)
print(mass_of_sun)
print(length_great_wall_of_china)


598
1.98963
21196


In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a column vector with 2 rows and 1 column using np.array() function
col_vec = np.array([[4],[3]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec. shape)


A column vector
 [[4]
 [3]]
Shape of vector= (2, 1)


In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec. shape)

A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a Zero row vector of dimension 3 using np.array() function
zero_vector_l=np.array([0,0,0])
print (zero_vector_l)
#Illustrating a Zero row vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print (zero_vector_2)
#Illustrating a Zero column vector of dimension 3 using np.zeros() and reshape() function
zero_vector_3=np.zeros(3).reshape(3,-1)
print (zero_vector_3)

[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a One vector of dimension 3 using np.array(} function
one_vector_1=np.array([1,1,1])
print (one_vector_1)
#Illustrating a One vector of dimension 3 using np.ones() function
one_vector_2=np.ones(3)
print (one_vector_2)
#Illustrating a column vector of ones of dimension 3 using np.ones() and reshape() function
one_vector_3=np.ones(3).reshape(3,-1)
print (one_vector_3)

[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np-.array() function
matrix_2x2 = np.array([[1, 2],(3, 4)])
matrix_3x3 = np.array([[1, 2, 3],
[4, 5, 6],
[8, 9, 10]])
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)


2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A= np.array([[2,-2],[3,1],[1,4]])
print(A)

[[ 2 -2]
 [ 3  1]
 [ 1  4]]


In [ ]:
# selecting an element at row index 2 and column index

[ ] #selecting an element at row index 2 and column index 1
print("Element of matrix A at index position [2,1] is", A[2,1])

Element of matrix A at index position [2,1] is 4


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
print("Matrix A:\n",A)
# Finding transpose of a matrix using the function transpose()
print("Matrix A Transpose: \n",np.transpose(A))

Matrix A:
 [[ 2 -2]
 [ 3  1]
 [ 1  4]]
Matrix A Transpose: 
 [[ 2  3  1]
 [-2  1  4]]
